#!/bin/bash

set -e

while : ; do
  option="$1"
  #echo "option is $option"
  case "$option" in
  -d)
      export DEBUG=y
      shift
      ;;
  *)
     break
     ;;
  esac
done

mkdir -p cbuild
cd cbuild
cmake -DCMAKE_BUILD_TYPE=Debug ../
make
make tests
cd ../


if [ -n "$DEBUG" ]; then
  echo
  set -x
  cbuild/spp -DTEST_ARG_1 -DTEST_ARG_2 -Dlorem_ipsum -Dyacc -I/home/dev/ \
    script1.sh script2.sh script3.sh
  set +x
  echo
fi
