#!/bin/bash

set -Ee

while : ; do
  option="$1"
  #echo "option is $option"
  case "$option" in
  -d)
      export DEBUG=y
      shift
      ;;
  -t)
      DO_TESTS=y
      shift
      ;;
  *)
     break
     ;;
  esac
done

mkdir -p cbuild
cd cbuild
if [ -n "$DEBUG" ];then
  cmake -DCMAKE_BUILD_TYPE=Debug ../
else
  cmake ../
fi
make
cd ../

if [ -n "$DO_TESTS" ]; then
  make tests
  tests/runtests
fi
