#!/bin/bash

set -Ee

show_help() {
  echo "Usage: $0 [option...]" >&2
  echo
  echo "   -d         Enable debug builds and the preprocessor verbose output"
  echo "   -t         Run tests"
  echo "   -v         Enable verbose output when running tests"
  echo
  exit 1
}

while : ; do
  option="$1"
  #echo "option is $option"
  case "$option" in
  -d)
      export DEBUG=y
      shift
      ;;
  -t)
      export DO_TESTS=y
      shift
      ;;
  -v)
      export DO_VERBOSE=y
      shift
      ;;
  -h)
      show_help
      ;;
  *)
     break
     ;;
  esac
done

mkdir -p cbuild
cd cbuild
if [ -n "$DEBUG" ];then
  cmake -DCMAKE_BUILD_TYPE=Debug ../
else
  cmake ../
fi
make
cd ../

if [ -n "$DO_TESTS" ]; then
  make tests
  tests/runtests
fi
