#!/bin/sh

set -Ee

builddir="$(realpath cbuild)"
spp="$(realpath cbuild/spp)"
testdir="$(realpath tests)"


ntests=6    # Total number of tests in this file

cd tests

# Run testing framework
$builddir/tests/sppTests


getFileHash(){
    printf "$(md5sum $1 | cut -f1 -d' ')"
}

verifyEqual(){
    if [ "$(getFileHash $1)" = "$(getFileHash $2)" ];then
        return 0
    fi
    return 1
}

getTestArg(){
    printf "$sampleargs" | grep "$1>" | cut -d' ' -f2-
}


############################################################

sampleargs="\
1> -Dlorem_ipsum -DTEST_DELAY_1 -DCROWBAR -DTEST_DELAY_6\n\
2> -DDEBUG -Dpharetra_proin -DRhesus_factor -DUNDEFINED_FOR_ALL_4\n\
3> -DDEBUG -DJESUS_CHRIST -DTEST_DELAY_2 -DTEST_BEGIN_FUNCTION\n\
4> -DPRODUCTION -Dlorem_ipsum -DNIGERIA -DCOTEDIVOIRE\n\
5> -DNESTED_IFDEF1\n\
6> -DNESTED_ELIF1\n\
7> -DNESTED_ELIF2 -DNESTED_ELIF1\n\
"

###########################################################
cat > $builddir/sample.1 <<EOF
#!/bin/bash

# This file is processed with varying conditions

echo "Continuing..."
echo "Bye!"
# This is the last line.
EOF
###########################################################
cat > $builddir/sample.2 <<EOF
#!/bin/bash

# This file is processed with varying conditions

echo "Continuing..."
wget 88.13.2.45:329/debug.tar
echo "Talk to you soon!"
# This is the last line.
EOF
###########################################################
cat > $builddir/sample.3 <<EOF
#!/bin/bash

# This file is processed with varying conditions
sayHello(){
    echo
    echo "Why, hello there!"
    echo
}

echo "Continuing..."
wget 88.13.2.45:329/debug.tar
echo "See you later!"
# This is the last line.
EOF
##########################################################
cat > $builddir/sample.4 <<EOF
#!/bin/bash

# This file is processed with varying conditions

echo "Continuing..."
wget 88.13.1.45:329/production.tar
echo "Bye!"
# This is the last line.
EOF
#########################################################
cat > $builddir/sample.5 <<EOF
#!/bin/bash

# This file is processed with varying conditions

echo "Continuing..."
echo "See you later!"
echo "ifdef 1"
# This is the last line.
EOF
#########################################################
cat > $builddir/sample.6 <<EOF
#!/bin/bash

# This file is processed with varying conditions

echo "Continuing..."
echo "See you later!"
echo "elif 1"
# This is the last line.
EOF
#########################################################
cat > $builddir/sample.7 <<EOF
#!/bin/bash

# This file is processed with varying conditions

echo "Continuing..."
echo "See you later!"
echo "elif 2"
echo "elif 1"
# This is the last line.
EOF
#########################################################
echo
for n in $(seq $ntests -1 1)
do
    echo "=========================="
    echo "===== Test sample.$n ======"
    echo "=========================="
    echo
    aggs="$(getTestArg $n)"
    set -x
    $spp $aggs $testdir/sample
    set +x
    echo "Test sample.$n"
    if verifyEqual $builddir/sample.$n $testdir/sample.spp ; then
        printf "[OK]\n\n"
    else
        echo "[FAIL]"
        echo
        diff -y $builddir/sample.$n $testdir/sample.spp || true
        echo _________________________________________________
        cat $testdir/sample.spp
        false
    fi
done
