#!/bin/bash

# This file is processed with varying conditions
#-- @ifdef (PRINT_START_DATE || FOOBAR) && CROWBAR
echo "$(date)"
#-- @endif
#-- @ifdef TEST_BEGIN_FUNCTION
sayHello(){
    echo
    echo "Why, hello there!"
    echo
}
#-- @endif

#-- @ifdef TEST_DELAY_5
sleep 5
#-- @endif
echo "Continuing..."
#-- @ifdef PRODUCTION
wget 88.13.1.45:329/production.tar
#-- @elif DEBUG
wget 88.13.2.45:329/debug.tar
#-- @endif
#-- @ifdef (CROWBAR || lorem_ipsum)
echo "Bye!"
#-- @elif pharetra_proin
echo "Talk to you soon!"
#-- @else
echo "See you later!"
#-- @ifdef NESTED_IFDEF1
echo "ifdef 1"
#-- @elif NESTED_ELIF1
#-- @ifdef NESTED_ELIF2
echo "elif 2"
#-- @endif NESTED_ELIF2
echo "elif 1"
#-- @endif NESTED_IFDEF1
#-- @endif (CROWBAR || lorem_ipsum)
#-- @endif lorem_ipsum
# This is the last line.